on: push # Trigger the workflow when pushing to any branch
  push:
    branches:
      - main

jobs:
  deployToMyVm:
    runs-on: ubuntu-latest # Specify the OS runner of the temporary vm

    steps:
      - name: Archive and Deploy via TAR
        run: |
          # Clone your private repo using your specific secret name tag
          git clone 'https://${{ secrets.PAT }}@github.com/Aadeife2021/HTML.git' HTML

          # Move into the repo directory
          cd HTML
          chmod 600 firewall-webserver.pem # Ensure the key has correct permissions.

          cd ..
          tar --exclude=HTML/.git -czf HTML.tar.gz HTML

          ls -lah

          # Copying the compressed file over to your live EC2 IP
          scp -i HTML/firewall-webserver.pem -o StrictHostKeyChecking=no HTML.tar.gz ubuntu@13.220.148.118:/var/www/

          # Extracting it cleanly into the server web root directory
          ssh -i HTML/firewall-webserver.pem -o StrictHostKeyChecking=no ubuntu@13.220.148.118 "sudo tar -xzf /var/www/HTML.tar.gz -C /var/www/"

          # Fixing target server system permissions
          ssh -i HTML/firewall-webserver.pem -o StrictHostKeyChecking=no ubuntu@13.220.148.118 "sudo chown -R ubuntu:www-data /var/www/HTML"
          ssh -i HTML/firewall-webserver.pem -o StrictHostKeyChecking=no ubuntu@13.220.148.118 "sudo chmod -R 755 /var/www/HTML"
