on:
  push:
    branches:
      - main

jobs:
  deployToMyVm:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Code to EC2 Server
        run: |
          # Clone your private repo using a personal access token
          git clone 'https://${{ secrets.PAT }}@github.com/Aadeife2021/HTML.git' HTML

          # Move into the repo directory
          cd HTML

          # remove the .git directory
          rm -rf .git

          # Ensure the key has correct permissions
          chmod 600 firewall-webserver.pem

          # copy the website files over to the webserver(EC2)
          scp -i firewall-webserver.pem -o StrictHostKeyChecking=no -r . ubuntu@13.220.148.118:/var/www/HTML

          # fix your permission
          ssh -i firewall-webserver.pem -o StrictHostKeyChecking=no ubuntu@13.220.148.118 "sudo chown -R ubuntu:www-data /var/www/HTML"
          ssh -i firewall-webserver.pem -o StrictHostKeyChecking=no ubuntu@13.220.148.118 "sudo chmod -R 755 /var/www/HTML"
